### ISSUE TITLE
Phylogenetic distance distributions : edge_node_distance

### ISSUE THREAD

**Issue by Ananya1006** [ChiLiubio/meconetcomp#10]
Hi Chi!
I have reconstructed three correlation networks for the three groups (based on Location for my dataset) and created the list as required. 

I want to compare the phylogenetic distances of paired nodes in edges for the already calculated modules of my networks and also check which are significantly different statistically. However, I am running into some errors after the edge_node_distance calculation.

Here's the code:

node_names <- unique(unlist(lapply(network_list, function(x){colnames(x$data_abund)})))
filter_network_list <- microeco::clone(datasett)
filter_network_list$otu_table <- filter_network_list$otu_table[node_names, ]
filter_network_list$tidy_dataset()
filter_network_list$phylo_tree
phylogenetic_distance <- as.matrix(cophenetic(filter_network_list$phylo_tree))
club_net <- edge_node_distance$new(network_list = network_list, dis_matrix = phylogenetic_distance, label = "+") #I only have + labels
club_net$data_table

club_net$cal_diff(method = "anova")
Error in `$<-.data.frame`(`*tmp*`, Measure, value = "Value") : 
  replacement has 1 row, data has 0
  
club_net <- edge_node_distance$new(network_list = network_list, dis_matrix = phylogenetic_distance, label = "+", with_module = TRUE, module_thres = 100)
club_net$cal_diff(method = "anova")
Error in `$<-.data.frame`(`*tmp*`, Measure, value = "Value") : 
  replacement has 1 row, data has 0

**Comment by ChiLiubio** [comment]
Hi. Please also attach `datasett`. Without it, I cannot reproduce the issue.

**Comment by ChiLiubio** [comment]
I found the node names in the network is not same with the labels in the phylogenetic tree. So your network is not created at ASV level? If so, it is impossible to compare the edges for those ASVs.
![图片](https://github.com/user-attachments/assets/9a0cece4-d02a-454e-b168-cbfe9cc2a542)

**Comment by Ananya1006** [comment]
Yes, my network was constructed at the genus level, and further modules were assigned.

goa #subset from my main microtable datasett
g_net <- trans_network$new(dataset = goa, cor_method = "spearman",filter_thres = 0.0001, taxa_level = "Genus")
g_net$cal_network(COR_p_thres = 0.05, COR_cut = 0.6)
g_pos_network <- g_net$subset_network(edge = "+")    # extracting only positive edges
g_net2 <- clone(g_net)
g_net2$res_network <- g_pos_network
g_net2$cal_module()
g_net2$cal_network_attr()
g_net2$get_node_table(node_roles = TRUE) 
g_net2$get_edge_table()
g_net2 #this object was fed into the network list along with two other networks

I wanted to check the phylogenetic distance profile and compare it across all the modules in my network constructed at the genus level, if that makes sense.
Now if I am to recreate my network at the default "OTU" level, then the whole structure would be different, including topological metric. If I am not wrong networks at the OTU level will have far more nodes than networks built at higher taxonomic levels because each OTU is treated as an individual entity, meaning a more complex network.

Is there any solution to this? Is it possible to map the OTU information to the Genus labels in the g_net2 object and then perform the comparsion?

**Comment by ChiLiubio** [comment]
Sorry I am not sure whether it is feasible, but at least it is not an easy task. If it's not feasible, you could compare the distribution of these edges at the phylum level, as phylogenetic distances often exhibit some correlation with taxonomy.

**Comment by Ananya1006** [comment]
Hi!
I was able to solve this problem. However I am not able to adjust the
significance letters in my plot. Here's the plot and the code:

library(magrittr)

#creating the network list with the updated microtable object
network_list <- list()
club_net <- clone(p)
#club_net$sample_table$ %<>% subset(Location == "Bhitarkanika")
club_net$sample_table <- subset(club_net$sample_table, Location ==
"Bhitarkanika")
club_net$tidy_dataset()
club_net <- trans_network$new(dataset = club_net, cor_method =
"spearman",filter_thres = 0.0001, taxa_level = "Genus")
club_net$cal_network(COR_p_thres = 0.05, COR_cut = 0.6)
network_list$Bhitarkanika <- club_net

club_net <- clone(p)
club_net$sample_table <- subset(club_net$sample_table, Location == "Goan
mangroves")
club_net$tidy_dataset()
club_net <- trans_network$new(dataset = club_net, cor_method =
"spearman",filter_thres = 0.0001, taxa_level = "Genus")
club_net$cal_network(COR_p_thres = 0.05, COR_cut = 0.6)
g_pos_network <- club_net$subset_network(edge = "+")
club_net$res_network <- g_pos_network
network_list$Goan_mangroves <- club_net

club_net <- clone(p)
club_net$sample_table <- subset(club_net$sample_table, Location ==
"Sundarbans")
club_net$tidy_dataset()
club_net <- trans_network$new(dataset = club_net, cor_method =
"spearman",filter_thres = 0.0001, taxa_level = "Genus")
club_net$cal_network(COR_p_thres = 0.05, COR_cut = 0.6)
# extract positive edges
s_pos_network <- club_net$subset_network(edge = "+")
club_net$res_network <- s_pos_network
network_list$Sundarbans <- club_net

#Combined networks for comparison
network_list

#Calculating modularity
network_list %<>% cal_module(undirected_method = "cluster_fast_greedy")
#Calculating topological properties
club_net <- cal_network_attr(network_list)
club_net
#Get node and edge properties of all networks
network_list %<>% get_node_table(node_roles = TRUE) %>% get_edge_table
network_list

#Phylogenetic distances - module wise
node_names <- unique(unlist(lapply(network_list,
function(x){colnames(x$data_abund)})))
filter_network_list <- microeco::clone(p)
filter_network_list$otu_table <- filter_network_list$otu_table[node_names, ]
filter_network_list$tidy_dataset()
filter_network_list$phylo_tree
# obtain phylogenetic distance matrix
phylogenetic_distance <-
as.matrix(cophenetic(filter_network_list$phylo_tree))
club_net <- edge_node_distance$new(network_list = network_list, dis_matrix
= phylogenetic_distance, label = "+", with_module = TRUE, module_thres = 0)
club_net$cal_diff(method = "anova") #For multiple labels, only anova can be
used

I tried to change the letters to shorter but still it shows the default set
of letters

club_net$res_diff$Letter <- c("A", "B", "C", "D", "D", "D",
"E","E","E","E","E","E","E","E",
              "E","E","E","E","E","E","E","E","E","E","E","E", "F","F","F",
              "F","F","F","G","H", "H")
g1 <- club_net$plot(add = "jitter",add_sig_label = Method, #barwidth = 0,
                    add_sig_text_size = 2.5, y_increase = 0.2) +
  ylab("Phylogenetic distance")
g1

**Comment by Ananya1006** [comment]
Noted. Thanks!
